backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images"
public_folder: "src/assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "pubDate", widget: "datetime" }
      - { label: "Update", name: "updatedDate", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image", name: "heroImage", widget: "string" }
